### ISSUE TITLE
Qlikview REST connector doesn't works with Risotto

### ISSUE THREAD

**Issue by newrochelle** [ralfbecher/q-risotto#4]
Hello,
I'm trying to follow what you wrote about using QlikView with the Qlik REST Connector to retrieve data from Qlik Sense.

Could you explan deeper each needed step ?

I can't find the hypercube just created before using Postman.

Thanks for your support.

Best Regards
Andrea

**Comment by ralfbecher** [comment]
The hypercube needs to be created an each call.

**Comment by mmahad19** [comment]
Hi,
I am trying to use Q-risotta to access Qlik sense apps. Could you clarify if Qlik Sense Server Integration step alone is sufficient and Qlik Core Integration can be skipped?

**Comment by ralfbecher** [comment]
Hi,
yes, Qlik Core is an alternate deployment.
